### ISSUE TITLE
ボタンUIの作成(2)　テキスト付ボタンを作成中...テキストがボックスの真ん中に表示されないのでその対処

### ISSUE THREAD

**Issue by moqumo** [p2hacks2022/pre-team09#10]

**Comment by n4muru** [comment]
https://processing.org/reference/textAlign_.html
こちら参考にしていただくと、CENTERがセンターしてないのがわかると思います。

**Comment by moqumo** [comment]
ありがとうございます！
textAscentやtextDescentが関わってそうなので頑張ってみます

**Comment by moqumo** [comment]
テキストボックスの上端のy座標に、textAscentとtextDesentの平均を足すと上手くいきました。まだ、コメントアウトもできていないので、明日pushしておきまするー。

**Comment by moqumo** [comment]
とりあえずコメントアウト終了。
