### ISSUE TITLE
ArrayListの多次元配列化が表れた。非常に難解だ

### ISSUE THREAD

**Issue by n4muru** [p2hacks2022/pre-team09#12]

**Comment by moqumo** [comment]
このサイトが参考になるかも？
<https://www.delftstack.com/ja/howto/java/create-a-2d-arraylist-in-java/>

**Comment by moqumo** [comment]
IntをIntegerに変換する方法？
<https://www.delftstack.com/ja/howto/java/convert-int-to-integer-in-java/>

**Comment by moqumo** [comment]
ArrayList<ArrayList<>>解決。
