### ISSUE TITLE
【アプリ開始時】信用度をテキストファイルから読み込む

### ISSUE THREAD

**Issue by moqumo** [p2hacks2022/pre-team09#45]

**Comment by n4muru** [comment]
float credit_input(){
  String[] credit_vessel = loadStrings("credit.txt");
  float x;
  x = float(credit_vessel[credit_vessel.length]);
  return x;
}
これで行けるのではないでしょうか？

**Comment by moqumo** [comment]
よくよく考えると、setupのごとに全データをもとに再計算しているので、不要だった
