### ISSUE TITLE
page02_Input_draw()がそもそも実行されていないみたいです。

### ISSUE THREAD

**Issue by n4muru** [p2hacks2022/pre-team09#55]
プリントが反応しないので、そもそも、page02_Input_draw()が実行されていません。確認お願いします。
setup側は問題なく実行されていました。

**Comment by moqumo** [comment]
了解です。issue-drawを作ってApp.pde内を修正します。

**Comment by n4muru** [comment]
わかりました。ひとまず無視してmouse_clickを進めて大丈夫そうですか？

**Comment by moqumo** [comment]
おけー

**Comment by n4muru** [comment]
原因ご教授ありがとうございます。ひとまず自分で勧めれるところまで進めます。
バグ修正頑張ってください。

**Comment by n4muru** [comment]
後ろのパネルに判定を吸われることが判明いたしました。
実行の際はパネルの合間を縫ってクリックしてください。
このバグの解消は後回しで、、、
